### ISSUE TITLE
Floatplane fighters is not in the improvement list

### ISSUE THREAD

**Issue by heidelbergBD** [ruhiel/ImprovementArsenalPlugin#3]
Thank you for contributing this nice plugin.

I recently found out that I can not look up for the floatplane fighers (like Type 2 Kai or Ro.44) in the menu when it's on the correct day. I can still improve it in the game, but it is not shown in the plugin list.

Thank you again.

Sincerely

**Comment by ruhiel** [comment]
@heidelbergBD 
Please confirm this issue because it corresponded with v1.0.13 release.

**Comment by heidelbergBD** [comment]
It's solved, thank you.
