### ISSUE TITLE
IATableList.csの更新

### ISSUE THREAD

**Issue by kancolleojisan** [ruhiel/ImprovementArsenalPlugin#4]
こんにちはgithub初心者です。初心者というかこのために登録しました。
C#はよくわかっていないので見よう見まねで書きましたが
https://pastebin.com/bE052vRa
よろしければお使いください。

それとこれでいいのかなと思いつつツールチップ表示も書きました。
ちょっとカテゴリ分けとか勝手に変えてしまっていますが
利用出来そうな部分がありましたら利用して頂けましたら幸いです。

・IATableList.cs
https://pastebin.com/y0pp3mVZ
・IATable.cs
https://pastebin.com/DPRFBjEE
・ImprovementArsenalInfo.cs
https://pastebin.com/7agtSKzw
・ImprovementArsenalInfoModel.cs
https://pastebin.com/wLt3xR8U
・UserControl1.xaml
https://pastebin.com/bh3cvAp9

**Comment by ruhiel** [comment]
@kancolleojisan 
issue立てありがとうございます。
本件、マージしてv1.0.13にてリリース致しましたのでご確認ください。

**Comment by kancolleojisan** [comment]
ご対応ありがとうございます。確認させて頂きました。
今後とも便利に利用させて頂きます。
またカテゴリ分けのご採用、感謝です。
