### ISSUE TITLE
IATableList.csの更新と修正

### ISSUE THREAD

**Issue by kancolleojisan** [ruhiel/ImprovementArsenalPlugin#5]
こんにちは。新年明けましておめでとうございます。
D型砲への対応と全体的な曜日の修正を行いました。
また今後確認しやすいように、テーブルの順序を変更しました。
よろしければ、お使い頂けましたら幸いです。

**Comment by ruhiel** [comment]
@kancolleojisan 
明けましておめでとうございます。
issue立てありがとうございます。

issueは課題・要望を議論する場ですので、本件はPull requestでお願いします。

**Comment by kancolleojisan** [comment]
ご返信ありがとうございます。
わかりました。とりあえず外部URL部分の記載を消します。プルリクの仕方は知りません。
手助けになればと思ったことが逆にご迷惑になってしまって申し訳ないです。
